"""empty message

Revision ID: 5b07067c95a3
Revises: 
Create Date: 2017-10-24 18:20:39.927767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b07067c95a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('html_url', sa.String(length=256), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('stargazers_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_stargazers_count'), 'repository', ['stargazers_count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_stargazers_count'), table_name='repository')
    op.drop_table('repository')
    # ### end Alembic commands ###
