from unittest.mock import patch, MagicMock
import json

from django.core.management import call_command
from django.test import TestCase

from githubsearch_api.models import Repository


class FetchgithubTests(TestCase):
    @patch('requests.get')
    def test_fetchgithub(self, mocked_get):
        """
        Ensure we can fetch data from github API v3.
        """
        example_response = {
            "total_count": 2,
            "incomplete_results": "false",
            "items": [
                {
                    "id": 85328233,
                    "name": "apistar",
                    "full_name": "encode/apistar",
                    "owner": {
                        "login": "encode",
                        "id": 19159390,
                        "avatar_url": "https://avatars1.githubusercontent.com/u/19159390?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/encode",
                        "html_url": "https://github.com/encode",
                        "followers_url": "https://api.github.com/users/encode/followers",
                        "following_url": "https://api.github.com/users/encode/following{/other_user}",
                        "gists_url": "https://api.github.com/users/encode/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/encode/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/encode/subscriptions",
                        "organizations_url": "https://api.github.com/users/encode/orgs",
                        "repos_url": "https://api.github.com/users/encode/repos",
                        "events_url": "https://api.github.com/users/encode/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/encode/received_events",
                        "type": "Organization",
                        "site_admin": "false"
                    },
                    "private": "false",
                    "html_url": "https://github.com/encode/apistar",
                    "description": "A smart Web API framework, designed for Python 3. 🌟",
                    "fork": "false",
                    "url": "https://api.github.com/repos/encode/apistar",
                    "forks_url": "https://api.github.com/repos/encode/apistar/forks",
                    "keys_url": "https://api.github.com/repos/encode/apistar/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/encode/apistar/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/encode/apistar/teams",
                    "hooks_url": "https://api.github.com/repos/encode/apistar/hooks",
                    "issue_events_url": "https://api.github.com/repos/encode/apistar/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/encode/apistar/events",
                    "assignees_url": "https://api.github.com/repos/encode/apistar/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/encode/apistar/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/encode/apistar/tags",
                    "blobs_url": "https://api.github.com/repos/encode/apistar/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/encode/apistar/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/encode/apistar/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/encode/apistar/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/encode/apistar/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/encode/apistar/languages",
                    "stargazers_url": "https://api.github.com/repos/encode/apistar/stargazers",
                    "contributors_url": "https://api.github.com/repos/encode/apistar/contributors",
                    "subscribers_url": "https://api.github.com/repos/encode/apistar/subscribers",
                    "subscription_url": "https://api.github.com/repos/encode/apistar/subscription",
                    "commits_url": "https://api.github.com/repos/encode/apistar/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/encode/apistar/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/encode/apistar/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/encode/apistar/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/encode/apistar/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/encode/apistar/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/encode/apistar/merges",
                    "archive_url": "https://api.github.com/repos/encode/apistar/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/encode/apistar/downloads",
                    "issues_url": "https://api.github.com/repos/encode/apistar/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/encode/apistar/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/encode/apistar/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/encode/apistar/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/encode/apistar/labels{/name}",
                    "releases_url": "https://api.github.com/repos/encode/apistar/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/encode/apistar/deployments",
                    "created_at": "2017-03-17T15:42:12Z",
                    "updated_at": "2017-10-27T01:13:27Z",
                    "pushed_at": "2017-10-27T03:39:57Z",
                    "git_url": "git://github.com/encode/apistar.git",
                    "ssh_url": "git@github.com:encode/apistar.git",
                    "clone_url": "https://github.com/encode/apistar.git",
                    "svn_url": "https://github.com/encode/apistar",
                    "homepage": "https://discuss.apistar.org/",
                    "size": 1853,
                    "stargazers_count": 2561,
                    "watchers_count": 2561,
                    "language": "Python",
                    "has_issues": "true",
                    "has_projects": "true",
                    "has_downloads": "true",
                    "has_wiki": "true",
                    "has_pages": "false",
                    "forks_count": 172,
                    "mirror_url": "null",
                    "archived": "false",
                    "open_issues_count": 77,
                    "forks": 172,
                    "open_issues": 77,
                    "watchers": 2561,
                    "default_branch": "master",
                    "score": 41.264866
                },
                {
                    "id": 8950398,
                    "name": "LXC-Web-Panel",
                    "full_name": "lxc-webpanel/LXC-Web-Panel",
                    "owner": {
                        "login": "lxc-webpanel",
                        "id": 3912425,
                        "avatar_url": "https://avatars2.githubusercontent.com/u/3912425?v=4",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/lxc-webpanel",
                        "html_url": "https://github.com/lxc-webpanel",
                        "followers_url": "https://api.github.com/users/lxc-webpanel/followers",
                        "following_url": "https://api.github.com/users/lxc-webpanel/following{/other_user}",
                        "gists_url": "https://api.github.com/users/lxc-webpanel/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/lxc-webpanel/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/lxc-webpanel/subscriptions",
                        "organizations_url": "https://api.github.com/users/lxc-webpanel/orgs",
                        "repos_url": "https://api.github.com/users/lxc-webpanel/repos",
                        "events_url": "https://api.github.com/users/lxc-webpanel/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/lxc-webpanel/received_events",
                        "type": "Organization",
                        "site_admin": "false"
                    },
                    "private": "false",
                    "html_url": "https://github.com/lxc-webpanel/LXC-Web-Panel",
                    "description": "LXC Web Panel repository",
                    "fork": "false",
                    "url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel",
                    "forks_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/forks",
                    "keys_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/teams",
                    "hooks_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/hooks",
                    "issue_events_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/events",
                    "assignees_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/tags",
                    "blobs_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/languages",
                    "stargazers_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/stargazers",
                    "contributors_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/contributors",
                    "subscribers_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/subscribers",
                    "subscription_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/subscription",
                    "commits_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/issues/comments{/number}",
                    "contents_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/merges",
                    "archive_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/downloads",
                    "issues_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/labels{/name}",
                    "releases_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/releases{/id}",
                    "deployments_url": "https://api.github.com/repos/lxc-webpanel/LXC-Web-Panel/deployments",
                    "created_at": "2013-03-22T11:17:26Z",
                    "updated_at": "2017-10-25T09:33:08Z",
                    "pushed_at": "2017-10-09T19:10:42Z",
                    "git_url": "git://github.com/lxc-webpanel/LXC-Web-Panel.git",
                    "ssh_url": "git@github.com:lxc-webpanel/LXC-Web-Panel.git",
                    "clone_url": "https://github.com/lxc-webpanel/LXC-Web-Panel.git",
                    "svn_url": "https://github.com/lxc-webpanel/LXC-Web-Panel",
                    "homepage": "http://lxc-webpanel.github.io/",
                    "size": 209,
                    "stargazers_count": 459,
                    "watchers_count": 459,
                    "language": "Python",
                    "has_issues": "true",
                    "has_projects": "true",
                    "has_downloads": "true",
                    "has_wiki": "false",
                    "has_pages": "false",
                    "forks_count": 174,
                    "mirror_url": "null",
                    "archived": "false",
                    "open_issues_count": 41,
                    "forks": 174,
                    "open_issues": 41,
                    "watchers": 459,
                    "default_branch": "0.2",
                    "score": 38.176037
                }
            ]
        }

        mocked_get.return_value = mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.text = json.dumps(example_response)

        self.assertEqual(Repository.objects.all().count(), 0)

        call_command('fetchgithub', '--last')

        repositories = Repository.objects.all()
        self.assertEqual(repositories.count(), 2)
